### ISSUE TITLE
Lesson 1-2

### ISSUE THREAD

**Issue by ghost** [Synd1cate/Synd1cate.github.io#1]
НЕЗАЧЕТ, в целом, визуально не плохо.
Второй пункт дз гласит - Информацию (текст, фото) заменяйте на свою, так мы сможем быстрее познакомиться ;) Критично! Исправить.

Мне не нравится то что твой центральный блок центрируется левым маржином. Критично! Исправить.

font-size: 0; решает проблему с отступом под фото. в етом дз не критично, дальше буду придираться.

почитать про высоту линий. в етом дз не критично, дальше буду придираться.

правильно использовать для позиционирования margin  а не padding. padding ето внутренний отступ.  в етом дз не критично, дальше буду придираться. почитать про отступы!!!

Проверено - 21.10.2015.

**Comment by Synd1cate** [comment]
Вчера внес правки, проверяй

**Comment by ghost** [comment]
Зачет!
