### ISSUE TITLE
Lesson 3

### ISSUE THREAD

**Issue by ghost** [Synd1cate/Synd1cate.github.io#2]
Незачет!

Главное меню, нет активного елемента.
Левое меню тоже самое. 
Фтуер тоже самое.

Главное меню, бекграунд градиентом, или картинкой.

нету тени для текста в главном меню.

Неплохо заюзал пример для левого меню. но зря старался. там просто для активного еллемента и на ховер стиль повесить надо)) переделаешь))

неправильная высота линий для текста.

для футрера для спана надо сделать больше лайн хейт, он должен быть таким как высота меню, тогда текст будет по центру блока http://joxi.ru/jgmv4eLu6GqvAa

размер шрифта цвет и все что к нему относиться задавать не для ul а для li или если есть тег "а" внутри li то к тегу "а".

не писать стиль для общего селектора, делать привязку к класу родителя.
например в футере есть спан, если потом еще будет в тексте спан, то все слетит. понял?
та же ситуация с текстом. 

Проверено 27.10.2015

**Comment by Synd1cate** [comment]
Поправил ошибки в ДЗ согласно замечаниям и перезалил

**Comment by ghost** [comment]
Незачет.

Убрать отступы http://joxi.ru/gkrDX9PFPlngrp

Градиент главного меню не тот. На ховере тоже самое.

В левом меню нету ховера.

Ето лишнее меню http://joxi.ru/752a7QGCV5y7r0 

http://joxi.ru/qVrw4QKulMMdmX ширину задать к левому меню, а еллементам 100%.

Проверено - 28.10.2015

**Comment by Synd1cate** [comment]
Поправил ошибки в ДЗ согласно замечаниям и перезалил

**Comment by ghost** [comment]
Зачет!

http://joxi.ru/WL21Pj7S7YGDmX одинаковые стили объединять.

Ширина документа у тебя больше чем надо!!!
Когда используешь паддингг не забывай по бокс сайзинг бродер бокс!!!

**Comment by Synd1cate** [comment]
Все поправил! 
бокс сайзинг бродер бокс - применил!
